title: Nicky Zimmerman
author:
  name: Nicky Zimmerman
  email: nicky.zi@nus.edu.sg
description: "Best coding hamster for her age group"

# Build settings
#remote_theme: jekyll/minima
theme: jekyll-theme-minimal
logo: photo_2025-11-11_16-46-46.jpg
